accounts/urls.py
from django.urls import path , include
from django.conf.urls import url
from .import views
from django.conf.urls.static import static
from django. urls import reverse_lazy


app_name = 'accounts'


urlpatterns = [
    url(r'^signup/$', views.signup_view, name= 'signup'),
    url(r'^login/$', views.login_view, name= 'login'),
    url(r'^logout/$', views.logout_view, name= 'logout'),
    #path('accounts/', include('django.contrib.auth.urls')),
    
    
]

articles/urls.py
from django.urls import path

from . import views

from django.urls import path
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings

#from django .contrib.auth import views as auth_views

app_name = 'articles'

urlpatterns = [
    path('',views.article_list, name ='list'),
    url(r'^create/$',views.article_create, name = 'create'),
    #url(r'^(?P<slug>[\w-]+)/$',views.article_details,name ='detail'),
    path('<slug:slug>/',views.article_details,name ='detail'),
    #path('password/', auth_views.PasswordChangeView.as_view(template_name ='accounts/password_reset_change.html')),
]

blog_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
        path('', include('articles.urls')),
        path('accounts/',include('accounts.urls')),
        path('users/',include('users.urls')),
        path('admin/', admin.site.urls),
    
]

users/urls.py
from django.urls import path, include
from django.conf.urls import url 
from django.conf import settings
from articles import views as article_views
from .views import MyPasswordChangeView, MyPasswordResetDoneView
from django. urls import reverse_lazy
#from django .contrib.auth import views as auth_views


from . import views

app_name ='users'

urlpatterns = [
    path('change_password/',MyPasswordChangeView.as_view(),name='password_change_view'),
    path('change_password/done/',MyPasswordResetDoneView.as_view(),name='password_change_done_view'),
]

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.utils.timezone  import now
from datetime import datetime
from django.utils import timezone



# Create your models here.
class Article(models.Model):
    '''
    date,author,address,slug,thubmnail
    '''
    title = models.CharField(max_length=500) 
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    author = models.ForeignKey(User,default=None,on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title

    
    def snippet(self):
        return self.body[:100] + ' ...'
    
    
    
class Comment(models.Model):
    post =models.ForeignKey(Article,on_delete=models.CASCADE,related_name ='comments')
    name = models.CharField(max_length=200)
    #email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(blank=True,null=True,help_text=('keep empty for activation'))
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering =['created_on']
        #abstract = False
        
        
    def __str__(self):
            return 'Comment {} by {} '.format ( self.body, self.name)
    

users/models.py
from django.db import models

# Create your models here.

articles/forms.py
from django import forms
from .import models
from django.forms import ModelForm
from .models import Comment
#from django import forms as formView




class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title','body','slug']
        
        
      
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields=('name','body')
        
      

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.http import HttpResponse
from django.contrib.auth import login, logout
from django.urls import reverse_lazy
from django.views.generic import FormView
#from .forms import PreferenceModelForm



def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user =form.save()
            #log user in
            login(request,user)

            
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request,'accounts/signup.html',{'form':form})
            

def login_view(request):
    #a post or get
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #log in the user
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
               return redirect('articles:list')
    else:
        form = AuthenticationForm()
        
    return render(request, 'accounts/login.html',{'form':form})

def logout_view(request):
    if request.method =='POST':
        logout(request)
        return redirect("articles:list")
    

articles/views.py
# Create your views here.
from django.shortcuts import render,redirect, get_object_or_404
from .models import Article
from .forms import CommentForm 
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .import forms
from django.urls import reverse 


def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request,'articles/articles.html',{'articles':articles})


@login_required(login_url ='/accounts/login/')
def article_details(request,slug,):
    template_name ='articles/article_detail.html'
    post = get_object_or_404(Article, slug=slug)
    comments =post.comments.filter(active=True)
    new_comment = None
    if request.method =='POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()

    else:
        comment_form = CommentForm()
        
    return render(request,template_name,{'post':post,'comments':comments,'new_comment':new_comment,'comment_form':comment_form})
    

#add a decorator.import decorator to redirect to login





@login_required(login_url ='/accounts/login/')
def article_create(request):
    if request.method =='POST':
        form = forms.CreateArticle(data=request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            #save to db
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
        
    form =forms.CreateArticle()
    return render(request,'articles/article_create.html',{'form':form})

users/views.py
from django.shortcuts import render
from django.shortcuts import render
from django.contrib.auth.views import PasswordChangeView, PasswordResetDoneView
from django. urls import reverse_lazy

# Create your views here.
class MyPasswordChangeView(PasswordChangeView):
    template_name ='users/password_change.html'
    success_url =reverse_lazy('users:password_change_done_view')
    
class MyPasswordResetDoneView(PasswordResetDoneView):
    template_name ='users/password_reset_done.html'

accounts/templates/accounts/login.html
{% extends 'articles/dashboard.html' %}
{% load static %}

{% block content%}
<br>
<br>
<br>
<div class='container p-3'>
<br>
<div class='row'>
<div class='col p-3'>
<img src="{% static 'images/image3.jpg' %}" height='500' width='650'>

</div>
<div class='col'>
<br>
<br>
<br>
<br>
<br>
<br>
<div class='container'>
<div class='container'>
<form class='site-form text-center' action='{% url 'accounts:login' %}' method='post'>
{% csrf_token%}
<h5 class=''>{{form.as_p}}</h5>
{% if request.GET.next %}
<input type='hidden' name='next' value='{{request.GET.next}}'>
{% endif %}
<input type='submit' name='' value='Log in' class='bg-dark text-white ml-3'>
<span class='text-center pl-1'><a href="{% url  'accounts:signup' %}" class='pr-2 text-dark'>Dont have an account? Register.</a></span>
</form>
</div>
</div>
</div>
</div>
<br>
<br>
<br>
</div>
</div>



{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'articles/dashboard.html' %}

{% block content%}
<br>
<br>
<div class='container p-3'>
<div class='container'>
<div class='row'>
<div class='col'>
<h2 class='text-center'>REGISTER</h2>
<br>
<br>
<br>
<form class='site-form' action='/accounts/signup/' method='post'>
{% csrf_token %}
<div class='container'>
{{form.as_p | linebreaks }}
<br>
<input type='submit' name='' value='signup' class='bg-dark text-white'>
</form>
</form>
</div>
</div>
</div>
</div>
</div>
<br>
<br>
<br>
<br>
<br>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'articles/dashboard.html' %}

{% block content%}
<br>
<br>
<br>
<br>
<br>
<div classs='container'>
<h2 class='text-center'>Create an Awesome a new Article</h2>
<div class='container'>
<form class="form-group container" action="{% url  'articles:create' %}" method="post">
{% csrf_token %}
<div class='container'>
<div class='container jumbotron bg-dark text-white text-center'>
<div class='container my-3 p-3'>
{{form.as_p }}
<input type='submit' value='Create'>
</div>
</div>
<div>
</form>
</div>
</div>
</div>
<br>
<br>
<br>
<br>
<br>
{% endblock %} 

articles/templates/articles/article_detail.html
{% extends 'articles/dashboard.html' %}

{% block content %}
       <!--<a class='text-center pt-3' href="{% url 'articles:list'%}">Article List</a>-->
       <br>
<div class='container-fluid'>
<div class='container'>
<div class='container'>
<div class='jumbotron'>
<h2 class='text-center text-dark text-uppercase'>{{post.title}}</h2>
<div class='row'>
<div class='col text-center pt-3'>
<p>{{post.body}}</p>
<p>{{post.date}}</p>
</div>
</div>
</div>
</div>
</div>
</div>


<div class='container'>
<h2 class='text-center text-dark'>{{article.title}}</h2>




<div class='container'>
<div class='jumbotron'>
{% if new_comment %}
<div class='container'>
<p class='bg-danger text-white text-uppercase text-center'>You Posted</p>
{% else %}
<h3>Leave a comment</h3>
<form method='post'>
{{ comment_form.as_p}}
{% csrf_token %}
<button type='submit'>Submit</button>
</form>
{% endif %}
</div>
</div>
</div>
</div>


<h2>{{ post.comments.count }}  Comments</h2>
{% for comment in comments %}
<ul class="list-group p-2">
<div class='row'>
<div class='col'>
  <li class="list-group-item pt-3">
  {{ comment.created_on}}
  <br>
   Name : <span class='text-uppercase'>{{ comment.name }}</span>
  <br>
  Commented: {{ comment.body}}
  <br>
  {{ article.author }} </li>
  </div>
  <div>
  </div>
  <div class="col"></div>
<div class="col"></div>

  </div>
</ul>

{% endfor %}
{% endblock %}

articles/templates/articles/articles.html
{% extends 'articles/dashboard.html' %}
{% load static %}

{% block content %}
<div class='container-fluid'>
<img src="{% static 'images/image6.jpg' %}" height='600' width='1400'>

</div>
<br>
<br>
<div class='container-fluid'>
<div class='container'>
 <h2 class='text-center text-uppercase'>Posts</h2>
<br>
<div class='row'>
{% for article in articles %}
<div class='col-md-6 pb-3'>
<div class="card" style="width:470px">
<!--<img class="card-img-top" src="img_avatar1.png" alt="Card image">-->
<div class="card-body">
<h3 class="card-title text-center"> <a href="{% url 'articles:detail' slug=article.slug %}" class='text-dark'>{{article.title}}</a></h3>
<p class="card-text text-center">{{article.snippet}}
<br>
{{article.date}}
</p>
<p class='text-center'>
<a href="{% url 'articles:detail' slug=article.slug %}" class="btn btn-dark">Read More</a>
</p>
</div>
</div>
</div>
{% endfor %}
</div>
</div>
</div>
<!--</div>-->
<br>
<br>
{% endblock %}

articles/templates/articles/dashboard.html
{% extends 'articles/main.html' %}
<h1 class='text-light'><a href="{% url 'articles:list'%}">Articles</a></h1>


{% block content %}




{% endblock %}

        
        

articles/templates/articles/main.html
<!DOCTYPE html>
<html class="no-js">
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
    <body>
    {% include 'articles/nav.html' %}
    

    {% block content%}


    {% endblock %}
    <nav class='bg-dark text-white text-center p-2'>
    <br>
    @My_Crud 2020.
    </nav>
    



        <script src=""></script>
    </body>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

articles/templates/articles/nav.html
<nav class="navbar navbar-expand-lg navbar-dark  bg-dark">
  <a class="navbar-brand text-light" href="{% url  'articles:list' %}">Inspire</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
   aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
    {% if user.is_authenticated %}
      <li class='nav-item active pt-2'>
            <a class='text-center pt-3 text-white' href="{% url 'articles:list'%}">Home</a>
            </li>
        <li class='nav-item active pt-2 '>
             <a class='text-center pt-3 pl-2 pr-3 text-white' href="{% url 'users:password_change_view' %}">Reset Password</a>
          </li>
      <li class="nav-item">
      <form class='logout-link' action="{% url 'accounts:logout' %}" method='post'>
      {% csrf_token %}
        <button type='submit' class='btn btn-dark '>Log out </button>
      </form>
      </li>
      <li class='pt-2'><a href="{% url  'articles:create'  %}" class='pl-3 text-white'>New Article</a></li>
      {% else%}
               <li class='nav-item active pt-1'>
                <a class='text-center pt-3 pl-2 pr-3 text-white' href="{% url 'accounts:login' %}">Login</a>
                </li>
                <li class='nav-item active pt-1'>
                <a class='text-center pt-3 pl-2 pr-3 text-white' href="{% url 'accounts:signup' %}">Register</a>
                </li>

      {% endif %}
    </ul>
  </div>
</nav>

users/templates/users/password_change.html
{% extends 'articles/dashboard.html' %}
{% load static %}

{% block title%}

{% endblock title %}
{% block content %}

<br>
<br>
<br>
<div class='container'>
<div class='container p-3 m-3 jumbotron bg-white'>
<div class='row'>
<div class='col p-3 text-center'>
<br>
<img src="{% static 'images/image4.jpg' %}" class='img-fluid'>
</div>
<div class='col pl-3 m-1'>
<h4 class='text-center'>Reset Password</h4>
<p style ='background:black'>___________</p>
<br>
<form action='' method='POST'>
{% csrf_token %}
{{ form.as_p }}
<input type='submit' value='submit' class='btn-dark'>
</form>
<br>
<p style ='background:black'>___________</p>

<br>
</div>
</div>
</div>
</div>
<br>
<br>


{% endblock content %}

users/templates/users/password_reset_done.html
{% extends 'articles/dashboard.html' %}
{% block title %}
<h2>Password Changed<h2>
{% endblock title %}

{% block content %}
<h2>Password has been changed.<h2>
<br>
<a href="{% url 'articles:list' %}"<button type='submit'>Home</button></a>
{% endblock content %}